/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Certification } from "./Certification";
export * as factories from "./factories";
export { Certification__factory } from "./factories/Certification__factory";
